group:
    resource: "@GroupBundle/Controller/"
    type:     annotation
    prefix:   /group

notification:
    resource: "@NotificationBundle/Controller/"
    type:     annotation
    prefix:   /notif

payement:
    resource: "@PayementBundle/Controller/"
    type:     annotation
    prefix:   /payement

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
